// ── DATA ──────────────────────────────────────────────────────────────────────

const STAGES = [
  { id:'G1',  min:90,  max:Infinity, rep:100,  label:'G1',  range:'≥90',   color:'#28A745', desc:'정상 또는 증가 (신장손상 지표 존재 시 CKD)' },
  { id:'G2',  min:60,  max:89.9,     rep:89.9, label:'G2',  range:'60–89', color:'#5BAD6F', desc:'경도 감소 (신장손상 지표 존재 시 CKD)' },
  { id:'G3a', min:45,  max:59.9,     rep:59.9, label:'G3a', range:'45–59', color:'#FF9F0A', desc:'경도~중등도 감소' },
  { id:'G3b', min:30,  max:44.9,     rep:44.9, label:'G3b', range:'30–44', color:'#FF6B00', desc:'중등도~중증 감소' },
  { id:'G4',  min:15,  max:29.9,     rep:29.9, label:'G4',  range:'15–29', color:'#FF3B30', desc:'중증 감소' },
  { id:'G5',  min:0,   max:14.9,     rep:14.9, label:'G5',  range:'< 15',  color:'#C0392B', desc:'신부전 — 신대체요법(투석/이식) 고려' },
];

const DRUGS = [
  {
    cat: '혈당강하제', imp: false,
    name: 'Metformin',
    ci_at: 30, ca_at: 45,
    threshold: 'GFR < 30 금기\n30–45 주의',
    reason: '신장 배설 저하로 젖산산증(lactic acidosis) 위험. GFR 45 이하에서 신규 처방 자제 권고.',
    alts: ['SGLT-2i (GFR 허용 시)', 'DPP-4i', 'Insulin'],
  },
  {
    cat: '혈당강하제', imp: true,
    name: 'Glibenclamide (1세대 SU)',
    ci_at: 30, ca_at: 45,
    threshold: 'GFR < 30 금기\n30–45 주의',
    reason: '활성 대사체 축적 → 지속성 저혈당 위험. GFR 45 이하 신규 처방 자제, GFR 30 미만 금기. CKD에서 가장 위험한 설폰요소제.',
    alts: ['Glipizide (단기작용 SU)', 'Gliclazide', 'DPP-4i'],
  },
  {
    cat: '혈당강하제', imp: true,
    name: 'SGLT-2 억제제 (Empagliflozin 등)',
    ci_at: 20, ca_at: 45,
    threshold: 'GFR < 20 금기\n20–45 혈당효과 감소',
    reason: 'GFR 저하 시 신장 포도당 여과량 감소로 혈당강하 효과 소실(GFR < 45). ※ KDIGO 2022: 심부전·CKD 신장보호 목적으로는 GFR 20까지 유지 권고 — 혈당 목적과 구분 필요.',
    alts: ['Insulin', 'DPP-4i'],
  },
  {
    cat: '혈당강하제', imp: false,
    name: 'DPP-4 억제제 (Sitagliptin 등)',
    ci_at: 0, ca_at: 45,
    threshold: 'Linagliptin 전 단계 가능\n타 DPP-4i GFR < 45 감량',
    reason: 'Linagliptin만 담즙 배설로 전 단계 감량 불필요. Sitagliptin·Saxagliptin 등은 GFR < 45~50에서 용량 감량 필수. 국시: "DPP-4i는 무조건 안전" 오해 주의.',
    alts: ['Linagliptin (신기능 무관)'],
  },
  {
    cat: '진통소염제', imp: true,
    name: 'NSAIDs (Ibuprofen, Naproxen 등)',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: 'PG 합성 억제 → 신혈류 감소 → AKI 유발. ACEi/ARB + 이뇨제와 병용 시 "triple whammy" 주의.',
    alts: ['Acetaminophen', 'Tramadol (용량 감량)'],
  },
  {
    cat: '진통소염제', imp: false,
    name: 'Ketorolac',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: '단기 사용에도 신독성 위험이 높은 NSAID. 신기능 저하 환자에서 더욱 위험.',
    alts: ['Acetaminophen'],
  },
  {
    cat: '항생제', imp: true,
    name: 'Aminoglycoside (Gentamicin, Amikacin)',
    ci_at: 0, ca_at: 60,
    threshold: 'GFR < 60 TDM 필수',
    reason: '신독성 및 이독성. TDM(혈중 농도 모니터링) 필수. Extended interval 투여 권장.',
    alts: ['Beta-lactam계', 'Fluoroquinolone (적응증 적합 시)'],
  },
  {
    cat: '항생제', imp: true,
    name: 'Vancomycin',
    ci_at: 0, ca_at: 60,
    threshold: 'GFR < 60 TDM 필수',
    reason: 'AUC/MIC 기반 TDM으로 용량·투여 간격 개별화 필요. 신독성 모니터링.',
    alts: ['Teicoplanin (용량 조정)', 'Linezolid'],
  },
  {
    cat: '항생제', imp: false,
    name: 'Nitrofurantoin',
    ci_at: 30, ca_at: 45,
    threshold: 'GFR < 30 금기\n30–45 주의',
    reason: '요중 농도 불충분으로 치료 효과 감소 + 말초신경병증 위험.',
    alts: ['Fosfomycin', 'Trimethoprim (GFR 허용 시)'],
  },
  {
    cat: '항생제', imp: false,
    name: 'Tetracycline (Doxycycline 제외)',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: 'BUN 상승 유발. Doxycycline은 담즙 배설로 신기능 저하에서 안전하게 사용 가능.',
    alts: ['Doxycycline'],
  },
  {
    cat: '심혈관계', imp: true,
    name: 'ACE inhibitor / ARB',
    ci_at: 0, ca_at: 30,
    threshold: 'GFR < 30 면밀 모니터링',
    reason: 'K⁺ 상승(고칼륨혈증) 주의. sCr 20–30% 이내 상승은 허용 범위. 급격한 GFR 저하 시 중단 고려.',
    alts: ['Amlodipine', 'Beta-blocker'],
  },
  {
    cat: '심혈관계', imp: true,
    name: 'Spironolactone',
    ci_at: 30, ca_at: 45,
    threshold: 'GFR < 30 금기\n30–45 주의',
    reason: '고칼륨혈증 위험. ACEi/ARB 병용 시 더욱 위험하므로 전해질 면밀 모니터링.',
    alts: ['Furosemide', 'Eplerenone (주의)'],
  },
  {
    cat: '심혈관계', imp: true,
    name: 'Digoxin',
    ci_at: 0, ca_at: 60,
    threshold: 'GFR < 60 TDM 필수',
    reason: '80% 신장 배설. TDM 필수. 치료 역치가 좁아 독성(부정맥, 오심) 위험.',
    alts: ['Beta-blocker', 'Amiodarone (적응증별)'],
  },
  {
    cat: '조영제', imp: true,
    name: '요오드 조영제 (CT)',
    ci_at: 0, ca_at: 30,
    threshold: 'GFR < 30 위험 증가',
    reason: 'CI-AKI(조영제 유발 급성 신손상) 위험. 수화 전처치 필수. GFR 저하 시 최소 용량 사용.',
    alts: ['MRI (Gadolinium, GFR 허용 시)', '비조영 영상'],
  },
  {
    cat: '조영제', imp: true,
    name: 'Gadolinium 조영제 (MRI)',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: 'NSF(신성전신섬유증) 위험. 대환형(macrocyclic) 제제가 상대적으로 안전.',
    alts: ['비조영 MRI', '요오드 조영제 CT (GFR 허용 시)'],
  },
  {
    cat: '항응고제', imp: true,
    name: 'Dabigatran',
    ci_at: 30, ca_at: 50,
    threshold: 'GFR < 30 금기\n30–50 주의',
    reason: '80% 신장 배설. GFR < 30 금기. 출혈 위험 증가.',
    alts: ['Apixaban (GFR ≥ 25)', 'Warfarin'],
  },
  {
    cat: '항응고제', imp: true,
    name: 'Rivaroxaban',
    ci_at: 15, ca_at: 30,
    threshold: 'GFR < 15 금기\n15–30 감량',
    reason: 'GFR < 15 금기. 15–30 구간에서 용량 감량 필요.',
    alts: ['Apixaban', 'Warfarin'],
  },
  {
    cat: '항응고제', imp: true,
    name: 'LMWH (Enoxaparin)',
    ci_at: 20, ca_at: 30,
    threshold: 'GFR < 20 금기\n20–30 주의',
    reason: 'GFR < 30 시 UFH(미분획 헤파린)로 전환 고려. 항Xa 모니터링.',
    alts: ['UFH (미분획 헤파린)'],
  },
  {
    cat: '기타', imp: true,
    name: 'Lithium',
    ci_at: 0, ca_at: 45,
    threshold: 'GFR < 45 TDM 필수',
    reason: '신성 요붕증 유발 가능. TDM 필수. 탈수 시 독성 위험 급증.',
    alts: ['Valproate', 'Lamotrigine'],
  },
  {
    cat: '기타', imp: true,
    name: 'Colchicine',
    ci_at: 10, ca_at: 30,
    threshold: 'GFR < 10 금기\n10–30 주의',
    reason: '근병증·신독성. GFR < 10 절대 금기. GFR 10–30 구간 용량 감량 및 모니터링 필요.',
    alts: ['NSAIDs (신기능 허용 시)', 'Corticosteroid'],
  },
  {
    cat: '기타', imp: true,
    name: 'Allopurinol',
    ci_at: 0, ca_at: 30,
    threshold: 'GFR < 30 용량 감량',
    reason: 'Oxypurinol 축적 → Stevens-Johnson 증후군 등 과민반응 위험.',
    alts: ['Febuxostat (신기능 무관)'],
  },
  {
    cat: '기타', imp: true,
    name: 'Methotrexate',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: '90% 신장 배설. 골수억제·점막염 위험. 엽산 보충 필수.',
    alts: ['Leflunomide', 'Hydroxychloroquine'],
  },
  {
    cat: '진통소염제', imp: true,
    name: 'Codeine / Tramadol',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: '활성 대사체(Morphine-6-glucuronide, O-desmethyltramadol) 신장 축적. 호흡억제·경련(tramadol) 위험. GFR 30 미만 금기.',
    alts: ['Acetaminophen', 'Buprenorphine (신기능 무관)'],
  },
  {
    cat: '항생제', imp: true,
    name: 'TMP-SMX (Trimethoprim-Sulfamethoxazole)',
    ci_at: 15, ca_at: 30,
    threshold: 'GFR < 15 금기\n15–30 주의',
    reason: 'Trimethoprim이 세뇨관 Cr 분비 억제 → sCr 위양성 상승(실제 GFR 감소 아님). 고칼륨혈증(K⁺ 보존) 주의. GFR < 15 금기.',
    alts: ['Fosfomycin', 'Nitrofurantoin (GFR ≥ 45)'],
  },
  {
    cat: '항생제', imp: true,
    name: 'Acyclovir / Valacyclovir',
    ci_at: 0, ca_at: 50,
    threshold: 'GFR < 50 감량 필수\n결정뇨 주의',
    reason: '신장 배설. GFR 저하 시 용량·투여 간격 조정 필수. 결정뇨로 인한 AKI 유발 가능 → 충분한 수화(hydration) 필수.',
    alts: ['용량 감량 후 동일 약제 유지'],
  },
  {
    cat: '심혈관계', imp: false,
    name: 'Thiazide 이뇨제 (Hydrochlorothiazide 등)',
    ci_at: 0, ca_at: 30,
    threshold: 'GFR < 30 효과 소실',
    reason: 'GFR < 30에서 세뇨관 분비 저하로 이뇨 효과 소실. 단독으로 부종·고혈압 조절 불가. Loop diuretic으로 전환 필요.',
    alts: ['Furosemide', 'Torsemide'],
  },
  {
    cat: '항응고제', imp: true,
    name: 'Apixaban',
    ci_at: 25, ca_at: 30,
    threshold: 'GFR < 25 금기\n25–30 주의',
    reason: '신장 배설 27%. DOAC 중 신기능 저하 시 상대적으로 안전. GFR < 25 또는 sCr ≥ 2.5 mg/dL 시 금기. 용량 기준: sCr ≥ 1.5 + 나이 ≥ 80 또는 체중 ≤ 60 kg 중 2가지 해당 시 감량.',
    alts: ['Warfarin (신기능 무관, INR 모니터링 필수)'],
  },
  {
    cat: '기타', imp: true,
    name: 'Gabapentin / Pregabalin',
    ci_at: 0, ca_at: 60,
    threshold: 'GFR < 60 감량 필수\n< 30 고용량 금지',
    reason: '100% 신장 배설. GFR 저하 시 과진정·혼수·호흡억제 위험. 국시 단골: GFR에 따라 투여 간격 연장 및 용량 적극 감량.',
    alts: ['저용량 유지 (GFR 기반 조정)'],
  },
  {
    cat: '기타', imp: true,
    name: 'Bisphosphonate (Alendronate 등)',
    ci_at: 35, ca_at: 45,
    threshold: 'GFR < 35 금기\n35–45 주의',
    reason: '골다공증 치료에 흔히 사용. FDA 라벨 기준 CrCl < 35 금기. GFR 저하 시 저칼슘혈증·신독성 위험. 골다공증 처방 전 반드시 신기능 확인.',
    alts: ['Denosumab (신기능 무관)', 'Raloxifene'],
  },
  {
    cat: '진통소염제', imp: true,
    name: 'Morphine',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: '활성 대사체 Morphine-6-glucuronide(M6G)가 신장 배설 의존 → CKD에서 축적 → 심각한 호흡억제. 오피오이드 중 CKD에서 가장 위험. Fentanyl(비활성 대사체, 간 배설)이 대체약물.',
    alts: ['Fentanyl (신기능 무관)', 'Buprenorphine'],
  },
  {
    cat: '기타', imp: true,
    name: 'Fenofibrate',
    ci_at: 30, ca_at: 60,
    threshold: 'GFR < 30 금기\n30–60 주의',
    reason: '신장 배설. CKD에서 근병증(rhabdomyolysis) 및 신기능 악화 위험. Statin은 CKD에서 사용 가능하나 Fibrate는 금기 — 이 대비가 국시 핵심 포인트.',
    alts: ['Statin (신기능 무관)', 'Omega-3'],
  },
];

const CATS = ['혈당강하제', '진통소염제', '항생제', '심혈관계', '조영제', '항응고제', '기타'];